### ISSUE TITLE
Data i målepunkter er forskudt

### ISSUE THREAD

**Issue by KajFRasmussen** [archaeodav/felttegn#11]
Data fordeles ikke optimalt i punkter. Datalinjen 
_531428.456,6227745.022,71.419,1450,A205.bs5 Kogestensgrube_
Ender som i følgende:

fid	        X		        Y		        Z	        PtID	        Kote	  FeatID	Attr
2254	531428.456	6227745.022	71.419	1450	A	  A205	bs5 Kogestensgrube

[Kote] bør vel være lig med [Z] og ikke få typeværdien "A"?

**Comment by KajFRasmussen** [comment]
"Forskudt" er måske ikke lige den rette term..

**Comment by KajFRasmussen** [comment]
![image](https://user-images.githubusercontent.com/77663465/129736437-cb3a3577-5f4e-4c18-b750-91056f5d6f0b.png)
Datatypen skrives i kote kolonnen, og bortset fra at det ikke er optimalt, så er de vigtige data, nemlig koordinater, nummer og note i de korrekte kolonner. Der er ret beset måske tale om en "funktion" og ikke en egentlig fejl...

**Comment by archaeodav** [comment]
Renamed _Kote_ to _Type_
