### ISSUE TITLE
Sten håndteres ikke

### ISSUE THREAD

**Issue by nesnejretep** [archaeodav/felttegn#12]

**Comment by karlhjalte** [comment]
Er der slet ikke nogen mulighed for at få sten til at virke?

**Comment by KajFRasmussen** [comment]
Måske sten systematisk SKAL nummereres nu. Fortløbende indenfor måledagen er så vidt jeg kan se tilstrækkeligt. 
Jeg får i hvert fald data ud ved at kode "-sten.1"; "-sten.2" osv.

**Comment by KajFRasmussen** [comment]
Men ikke i den nye version...

**Comment by KajFRasmussen** [comment]
Så vidt jeg kan se er den også gal med -snit

**Comment by archaeodav** [comment]
@karlhjalte @KajFRasmussen 
Could you provide a full example file so I can test this?

**Comment by archaeodav** [comment]
Fixed in version 0.28. 
I'll close this, but please test
