### ISSUE TITLE
Ikke alle anlæg oprettes

### ISSUE THREAD

**Issue by karlhjalte** [archaeodav/felttegn#13]
Jeg forstår ikke hvad syntaksfejl kan være, da den undlader visse anlæg og laver identifikation om i visse tilfælde. Det er dog ikke konsekvent for alle opmålinger, men særligt tilfældet med denne opmåling. 

Nogen der har en ide om hvad hvilken syntaksfejl der opstår? Der er ikke "sten" i, og ved andre filer er der ingen problemer
[HOM34444_20210316_original.txt](https://github.com/archaeodav/felttegn/files/6646494/HOM34444_20210316_original.txt)
[HOM34444_20210316_udenmellemrum.txt](https://github.com/archaeodav/felttegn/files/6646495/HOM34444_20210316_udenmellemrum.txt)

mvh. Hjalte

**Comment by KajFRasmussen** [comment]
Jeg opdagede også lige en sag hvor i hvert fald det sidste anlæg ikke var med i det genererede, på trods af at syntaks var korrekt... Måske er det er ret generelt problem, jeg synes nemlig også -snit kun kommer med over en sjælden gang imellem...

**Comment by archaeodav** [comment]
> Jeg opdagede også lige en sag hvor i hvert fald det sidste anlæg ikke var med i det genererede med version 0.25. Det på trods af at syntaks var korrekt og det har virket med en tidligere version...
> Måske er det er ret generelt problem, jeg synes nemlig også -snit kun kommer med over en sjælden gang imellem, og sten slet ikke...

Separate issue. Please open a new issue with example data.

**Comment by archaeodav** [comment]
> Jeg forstår ikke hvad syntaksfejl kan være, da den undlader visse anlæg og laver identifikation om i visse tilfælde. Det er dog ikke konsekvent for alle opmålinger, men særligt tilfældet med denne opmåling.
> 
> Nogen der har en ide om hvad hvilken syntaksfejl der opstår? Der er ikke "sten" i, og ved andre filer er der ingen problemer
> [HOM34444_20210316_original.txt](https://github.com/archaeodav/felttegn/files/6646494/HOM34444_20210316_original.txt)
> [HOM34444_20210316_udenmellemrum.txt](https://github.com/archaeodav/felttegn/files/6646495/HOM34444_20210316_udenmellemrum.txt)
> 
> mvh. Hjalte

Ok. Found the problem. The kote / all points file was overwriting the anlæg IDs. Will be fixed on next release, wheraupon I will will close this as resolved.

**Comment by archaeodav** [comment]
Fixed in version 0.28
