### ISSUE TITLE
En fil der ikke giver problemer i mapdigi, men giver problemer i felttegn

### ISSUE THREAD

**Issue by karlhjalte** [archaeodav/felttegn#15]
Hej

Ved autoopret af denne fil, giver felttegn et næsten ubrugeligt returresultat. Der sker noget meget mærkeligt med A1, som bliver til et polygon der ikke kan færdigbearbejdes. Filen er kørt igennem som både geopackage og .tab fil, men begge resultater er ikke gode. Jeg har forsøgt at optimere .csv-filen til mere Felttegn venlig med punktummer i stedet for mellemrum, men uden forbedring.
[HOM3720_20210915 - MI.csv](https://github.com/archaeodav/felttegn/files/7192581/HOM3720_20210915.-.MI.csv)
[HOM3720_20210915 - QGIS.csv](https://github.com/archaeodav/felttegn/files/7192582/HOM3720_20210915.-.QGIS.csv)

Prøv at køre HOM3720_20210915.-.MI.csv igennem både MI mapdigi og QGIS felttegn, og det er tydeligt at der er nogle større problemer i forhold til videre redigering. Igennem mapdigi bliver resultatet muligt at redde, men i Felttegn kan man ikke rigtigt komme videre

mvh. Hjalte

**Comment by archaeodav** [comment]
![Screenshot_2021-09-22_12-21-01](https://user-images.githubusercontent.com/67315670/134326924-eebbfbc0-e87e-4a1f-9bbe-158f2cd3684f.png)

Not sure what you mean- is this how A1 should look?

**Comment by karlhjalte** [comment]
Nope. Signal was bad for A1, because of trees. The points were supposed to be along the border of the trench. However, that is of course not the problem. Try to change the outline of A1. It resets itself, and the polygon cannot be altered it seems. Same goes for the little trench next to it. It is not possible to change the outline by nodes (at least not possible for me)

**Comment by archaeodav** [comment]
![Screenshot_2021-09-22_13-56-14](https://user-images.githubusercontent.com/67315670/134339245-620b458a-617b-4087-97d6-c2de0d3e33bc.png)

No problem here- either using the reshape tool or by editing vertices.

**Comment by karlhjalte** [comment]
Strange. For me it kept resetting back to original shape once you saved.

**Comment by archaeodav** [comment]
Might be worth trying the new version- 0.28 is on git but not yet approved by the QGIS plugin repo, although I couldn't replicate this in 0.25 either.

Which QGIS version are you using? Does it do this with other layers?

**Comment by karlhjalte** [comment]
Yeah... i'm running 0.25. Didn't notice it was not 0.28 in the repository. QGIS version is 3.16.11 (long term stable) 

I will try to run it again and see if I can replicate

How about the generic generated ID for some of the features. All of the features have an ID, but one was double. Can't it just display output even though ID is double, or do you need to troubleshoot before to make certain nothing has same ID (number)? Sometimes as well, features are disconnected with same ID, ie. layer cut by drain

**Comment by archaeodav** [comment]
> How about the generic generated ID for some of the features. All of the features have an ID, but one was double. Can't it just display output even though ID is double, or do you need to troubleshoot before to make certain nothing has same ID (number)? Sometimes as well, features are disconnected with same ID, ie. layer cut by drain

See issue #8. Fix coming shortly

**Comment by archaeodav** [comment]
Fault not replicable
