### ISSUE TITLE
Ver. 0.25 STEN oprettes ikke, LAG oprettes ikke

### ISSUE THREAD

**Issue by HugoHvidSorensen** [archaeodav/felttegn#16]
I version 0.25:
STEN oprettes ikke (bliver i MapInfo oprettet i "Anlæg_trans" uden navn/nummer i feltet  Anlægsangivelse og "Sten" i feltet  Note
Lag opretteses ikke (det er sidste "feature" i opmålingsfilen (laget "Lag_trans" generereres af MapDigi)

Har vedhæftet en Zip med Felttegn-generering i mappen "2021-03-02" og en version med MapDigi i "2021-03-02MapDigi"
[FeltTegnEksperimenter.zip](https://github.com/archaeodav/felttegn/files/7208446/FeltTegnEksperimenter.zip)

**Comment by archaeodav** [comment]
Duplicate of #12

**Comment by HugoHvidSorensen** [comment]
Sorry, but "LAG" does not seem to be mentioned in #12 ;-)

**Comment by archaeodav** [comment]
-LAG is a separate issue. Please open a new issue. However, both should be fixed in latest version
