### ISSUE TITLE
Prefix issues

### ISSUE THREAD

**Issue by karlhjalte** [archaeodav/felttegn#33]
Is it possible to have a possibility for including or excluding the prefix in front of the number, ie. 1000 instead of A1000 etc. 

Because, generally we don't use prefix

**Comment by archaeodav** [comment]
Yes- you can set the prefix to "" in the layer_definition.json file in the plugin directory for the appropriate layer. 

This file lets you configure a lot of stuff, such as which codes to use, appearance of layers etc. Currently everything uses the default configuration, but the intention is to add the option of each museum being able to add their own configurations to this file which will override the defaults.

**Comment by archaeodav** [comment]
New in version 1.2: Functionality to override the default configuration. Currently everything is under the 'default' museum, but you can now add layers, codes or styles in the JSON file under a 3 letter museum code and these will override those in the default,

The museum code can now be specified in a dropdown (not yet fully populated), or set to auto. Auto uses the first 3 characters of the input filename to set the museum.
