### ISSUE TITLE
_Kote

### ISSUE THREAD

**Issue by rensefar** [archaeodav/felttegn#35]
problemer med oprettelse af punkter i laget kote 

punkterne optræder dog i laget AllePunkter 

[fhm6267_20211126.csv](https://github.com/archaeodav/felttegn/files/7692315/fhm6267_20211126.csv)

**Comment by archaeodav** [comment]
Suggest that these are instead taken from AllePunkter in the near term- the fix for this will take a while.

**Comment by archaeodav** [comment]
Will add option for z export for all features

**Comment by archaeodav** [comment]
Fixed in upcoming release 1.23
