### ISSUE TITLE
-KOTE layer

### ISSUE THREAD

**Issue by L-CB** [archaeodav/felttegn#41]
When running af CSV-file through FeltTegn, the layer -KOTE comes through with data in only fig, date and method. It would be very useful if the attributetable for the layer was expanded to contain X, Y and Z for the layer. The layer doesn't really make sense otherwise :-).
Lars/ArkVest

**Comment by archaeodav** [comment]
Fixed in upcoming release 1.23

**Comment by archaeodav** [comment]
Duplicate of #35
