### ISSUE TITLE
Danish characters in field names in MapInfo export

### ISSUE THREAD

**Issue by nesnejretep** [archaeodav/felttegn#43]
I guess MapInfo uses ANSI or some other Micro$oft-encoding and not UTF-8.
![Mi issue](https://user-images.githubusercontent.com/5351637/167385367-19682b6f-afd1-493e-ad44-a8ed9eccc97f.png)

**Comment by archaeodav** [comment]
[Looks easy enough](https://gdal.org/drivers/vector/mitab.html), but earlier versions of MI don't like UTF-8- I'll try ISO-8859-1 or CP-1252

**Comment by archaeodav** [comment]
Fixed. Will close on upload of next update.
