### ISSUE TITLE
Museumskode

### ISSUE THREAD

**Issue by L-CB** [archaeodav/felttegn#46]
The newly reintroduced feature of "Museumskode" and "Journal" doesn't add the fields to the "AllePunkter"-coloumn. It appears on all other layers I've tested.
I'm using version 1.24, experimental.

Lars/ArkVest

**Comment by archaeodav** [comment]
Thanks. I'll fix this in v1.26.

**Comment by archaeodav** [comment]
Also doesn't include Metode, Dato or Opmåler...

**Comment by archaeodav** [comment]
fixed in 1.26.

Pending release on QGIS repo.
