### ISSUE TITLE
Håndtering af dobbeltnummerering

### ISSUE THREAD

**Issue by nesnejretep** [archaeodav/felttegn#8]
Den gamle MapDigi ændrede alle identifikationstegn til upper case. Det gør felttegn ikke, og det kan give dobbeltnumre!!! (A237 og a237 er unikke set fra Qgis' synspunkt). Til gengæld er der ingen advarsler hvis der ER dobbeltnumre: Så genereres der bare mærkelige numre til forekomst nummer to. Det kan hurtigt blive uoverskueligt ved anlægsrige udgravninger…

**Comment by KajFRasmussen** [comment]
Der burde også genereres en advarsel hvis Qgis er nødt til at generere et unikt nummer. Som det er kan dobbeltnumre være svære at finde (om end nemmere end i MapInfo)...

**Comment by archaeodav** [comment]
Should be fixed in v0.29
