### ISSUE TITLE
Anlæg kan ikke deles, da det ikke er MultiPolygon

### ISSUE THREAD

**Issue by nesnejretep** [archaeodav/felttegn#9]
Anlæg (og grøfter) kan med den valgte geometritype ikke deles i flere dele, og det mener jeg er et stort problem ved anlæg der f.eks. skæres af dræn. En løsning kunne være at anvende "Multipolygon" til disse i stedet for "Polygon" som det er tilfældet lige nu.

**Comment by KajFRasmussen** [comment]
Det vil jeg gerne tilslutte mig. Det bliver MEGET bøvlet at lave forundersøgelser, hvor det i reglen ofte sker anlæg skærer igennem hinanden. Som det er bliver man nødt til at lave passager udenom f.eks. dræn, så områder kan hænge sammen... -duer ikke!

**Comment by KajFRasmussen** [comment]
En lworkaraound for brugeren efter den ulovlige deling, kan være at skille synderen op i enkelanlæg som derfor får hver sin "fid", men samme anlægs- / grøft-nummer. Det er et komforttab, men data kan heldigvis stadig knyttes til andet data og analyseres.

**Comment by KajFRasmussen** [comment]
Anlægslag og Feltlag er nu af Multipolygon typen, som opfører sig mere som vi er vant til :-)

**Comment by archaeodav** [comment]
We're not going to force multipolygon at this stage- with unvalidated data like this it can cause problems with topological operations that we're using to validate geometries. 

What we are going to do is add an option to convert to multipolygon with the upcoming create master / import to master function that will do some other topological stuff like trimming _Anæg_ polygons to _Felt_ extents and handling duplicate geometries.
